apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: prediction-api
  type: LoadBalancer
  ports:
    - port: 8005
      targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: prediction-api
          image: chineidu/api_service:v1
          imagePullPolicy: IfNotPresent # default
          resources:
            limits:
              memory: "3Gi" # 3Gb
              cpu: "3000m"  # 3 cores
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            periodSeconds: 10
            initialDelaySeconds: 5
          ports:
            - containerPort: 8005
