apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: prediction-api
  type: LoadBalancer
  ports:
    - port: 8005
      targetPort: 8005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction-api
  template:
    metadata:
      labels:
        app: prediction-api
    spec:
      containers:
        - name: prediction-api
          image: chineidu/mlops:v3
          imagePullPolicy: IfNotPresent # default
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 5
          ports:
            - containerPort: 8000
