version: "3.8"

services:
  prediction:
    build:
      context: ./
      dockerfile: Dockerfile
    image: api_service:v1
    container_name: pred_app
    ports:
      - "8000:8005"
    volumes:
      - ./saved_model:/opt/saved_model # Mount the current directory to '/opt' w/in the container
